### ISSUE TITLE
ImportError: No module named utils

### ISSUE THREAD

**Issue by josketres** [lorin/mezzanine-example#3]
Hi, I'm following the example of the chapter 6 of the ansible-up-and-running book and I got an error in the task `sync the database, apply migrations, collect static content`.
I tried ssh into the vagrant machine and execute the command by myself and this is what i got:
```
(mezzanine-example)vagrant@vagrant-ubuntu-trusty-64:~/mezzanine-example/project$ ./manage.py syncdb --noinput
Traceback (most recent call last):
  File "./manage.py", line 28, in <module>
    execute_from_command_line(sys.argv)
  File "/home/vagrant/mezzanine-example/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 399, in execute_from_command_line
    utility.execute()
  File "/home/vagrant/mezzanine-example/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 392, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/vagrant/mezzanine-example/local/lib/python2.7/site-packages/django/core/management/base.py", line 242, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/home/vagrant/mezzanine-example/local/lib/python2.7/site-packages/django/core/management/base.py", line 284, in execute
    self.validate()
  File "/home/vagrant/mezzanine-example/local/lib/python2.7/site-packages/django/core/management/base.py", line 310, in validate
    num_errors = get_validation_errors(s, app)
  File "/home/vagrant/mezzanine-example/local/lib/python2.7/site-packages/django/core/management/validation.py", line 34, in get_validation_errors
    for (app_name, error) in get_app_errors().items():
  File "/home/vagrant/mezzanine-example/local/lib/python2.7/site-packages/django/db/models/loading.py", line 196, in get_app_errors
    self._populate()
  File "/home/vagrant/mezzanine-example/local/lib/python2.7/site-packages/django/db/models/loading.py", line 78, in _populate
    self.load_app(app_name)
  File "/home/vagrant/mezzanine-example/local/lib/python2.7/site-packages/django/db/models/loading.py", line 99, in load_app
    models = import_module('%s.models' % app_name)
  File "/home/vagrant/mezzanine-example/local/lib/python2.7/site-packages/django/utils/importlib.py", line 40, in import_module
    __import__(name)
  File "/home/vagrant/mezzanine-example/local/lib/python2.7/site-packages/compressor/models.py", line 1, in <module>
    from compressor.conf import CompressorConf  # noqa
  File "/home/vagrant/mezzanine-example/local/lib/python2.7/site-packages/compressor/conf.py", line 5, in <module>
    from django.template.utils import InvalidTemplateEngineError
ImportError: No module named utils
```

Can you give me some support to fix this?

**Comment by josketres** [comment]
I saw there's a pull request to fix this issue.

If it isn't merged yet you can change the repo _url in your playbook to 
`git@github.com:vinisbad/mezzanine-example.git` to continue testing the example from the book.
